# culture_tips.py

tips = {
    'en': "🇺🇸 English (US/UK)\n- Handshakes are common.\n- Maintain eye contact.\n- Tipping is expected in the US (~15-20%).",
    'fr': "🇫🇷 French\n- Greet with 'Bonjour'.\n- Cheek kissing common among friends.\n- Be formal in professional settings.",
    'es': "🇪🇸 Spanish\n- Use formal titles (Señor, Señora).\n- Embrace cheek kisses in informal settings.\n- Late dinners are common.",
    'de': "🇩🇪 German\n- Be punctual.\n- Use formal greetings.\n- Direct communication is appreciated.",
    'hi': "🇮🇳 Hindi (India)\n- Use 'Namaste' with a slight bow.\n- Avoid left hand in exchanges.\n- Respect elders with formal speech.",
    'ja': "🇯🇵 Japanese\n- Bow to greet.\n- Remove shoes indoors.\n- Silence is often seen as polite.",
    'zh': "🇨🇳 Chinese (Mandarin)\n- Avoid gifts in sets of 4.\n- Use both hands for offering items.\n- Address with titles and surnames.",
    'ru': "🇷🇺 Russian\n- Firm handshake with eye contact.\n- Remove gloves before shaking hands.\n- Toasting is a cultural norm.",
    'it': "🇮🇹 Italian\n- Warm greetings with handshakes or kisses.\n- Dressing well is important.\n- Meals are social events.",
    'pt': "🇵🇹 Portuguese (Portugal/Brazil)\n- Greet with kisses or handshakes.\n- Family is central.\n- Avoid overly direct communication.",
    'ar': "🇦🇪 Arabic\n- Greet with 'As-salamu alaykum'.\n- Right hand only for eating and greeting.\n- Maintain modest attire in public.",
    'bn': "🇧🇩 Bengali\n- Greet with 'Nomoskar'.\n- Remove shoes before entering homes.\n- Use right hand for giving and receiving.",
    'bg': "🇧🇬 Bulgarian\n- Nod for 'No' and shake head for 'Yes'.\n- Bring flowers for the host (odd number).\n- Toasting is common at meals.",
    'zh-TW': "🇹🇼 Chinese (Traditional)\n- Address elders formally.\n- Offer items with both hands.\n- Don’t stick chopsticks upright in rice.",
    'hr': "🇭🇷 Croatian\n- Greet with a firm handshake.\n- Respect elders with polite address.\n- Bring a small gift when visiting homes.",
    'cs': "🇨🇿 Czech\n- Remove shoes when entering homes.\n- Greet with a simple handshake.\n- Toast before drinking.",
    'da': "🇩🇰 Danish\n- Be punctual.\n- Danes value modesty.\n- Remove shoes inside homes.",
    'nl': "🇳🇱 Dutch\n- Be direct but polite.\n- Greet with a handshake.\n- Splitting bills is common (going Dutch).",
    'et': "🇪🇪 Estonian\n- Quietness is appreciated.\n- Handshakes are customary.\n- Remove shoes indoors.",
    'tl': "🇵🇭 Filipino (Tagalog)\n- Use 'Po' and 'Opo' as signs of respect.\n- Bring gifts when visiting homes.\n- Handshakes and smiles are common greetings.",
    'fi': "🇫🇮 Finnish\n- Value personal space.\n- Silence is comfortable.\n- Sauna is an essential social experience.",
    'el': "🇬🇷 Greek\n- Greet with a firm handshake.\n- Offer gifts when invited home.\n- Conversation is lively and expressive.",
    'gu': "🇮🇳 Gujarati\n- Greet with 'Jai Shri Krishna' or 'Namaste'.\n- Remove shoes before entering homes.\n- Right hand is used for eating.",
    'he': "🇮🇱 Hebrew\n- Shaking hands is standard.\n- Business dress is formal.\n- Avoid business meetings on Fridays or Saturdays.",
    'hu': "🇭🇺 Hungarian\n- Firm handshake for greetings.\n- Avoid clinking beer glasses.\n- Address with titles and surnames.",
    'id': "🇮🇩 Indonesian\n- Salam (greeting) with slight bow.\n- Use both hands for giving items.\n- Avoid pointing with fingers.",
    'ko': "🇰🇷 Korean\n- Bow to greet.\n- Hand objects or business cards with two hands.\n- Elders are shown high respect.",
    'lv': "🇱🇻 Latvian\n- Handshakes for greetings.\n- Avoid whistling indoors.\n- Bring flowers in odd numbers when visiting.",
    'lt': "🇱🇹 Lithuanian\n- Shake hands with eye contact.\n- Gifts for hosts are appreciated.\n- Respect personal space.",
    'ms': "🇲🇾 Malay\n- Greet with a gentle handshake.\n- Use right hand always.\n- Dress modestly in public areas.",
    'ml': "🇮🇳 Malayalam\n- Greet with 'Namaskaram'.\n- Remove shoes before entering homes.\n- Elders are addressed respectfully.",
    'mr': "🇮🇳 Marathi\n- Greet with 'Namaskar'.\n- Respect elders with formal language.\n- Remove shoes before entering homes.",
    'mn': "🇲🇳 Mongolian\n- Offer a light handshake.\n- Present gifts with both hands.\n- Avoid stepping over someone’s outstretched legs.",
    'ne': "🇳🇵 Nepali\n- Greet with 'Namaste' and palms together.\n- Use right hand for giving and receiving.\n- Remove shoes before entering homes.",
    'no': "🇳🇴 Norwegian\n- Punctuality is important.\n- Shake hands for greetings.\n- Personal space is respected.",
    'fa': "🇮🇷 Persian (Farsi)\n- Greet with 'Salam'.\n- Close friends kiss on the cheeks.\n- Giving gifts is appreciated.",
    'pl': "🇵🇱 Polish\n- Greet with a firm handshake.\n- Address people with titles.\n- Bring flowers for hosts (odd numbers only).",
    'pa': "🇮🇳 Punjabi\n- Greet elders with 'Sat Sri Akal'.\n- Remove shoes before entering homes or temples.\n- Respect is emphasized for family and elders.",
    'ro': "🇷🇴 Romanian\n- Handshakes are common.\n- Give flowers to your host.\n- Address people formally by titles.",
    'sr': "🇷🇸 Serbian\n- Shake hands for greetings.\n- Bring a small gift for hosts.\n- Remove shoes entering homes.",
    'si': "🇱🇰 Sinhala\n- Greet elders with 'Ayubowan'.\n- Remove shoes before entering homes.\n- Hand food or gifts with right hand.",
    'sk': "🇸🇰 Slovak\n- Address people formally.\n- Shake hands for introductions.\n- Bring flowers or chocolate to hosts.",
    'sl': "🇸🇮 Slovenian\n- Greet with a firm handshake and smile.\n- Bring wine or flowers for hosts.\n- Respect privacy and personal space.",
    'sw': "🇰🇪 Swahili\n- Greet with 'Jambo' or handshake.\n- Elders are shown respect.\n- Giving with right hand is proper.",
    'sv': "🇸🇪 Swedish\n- Punctuality is important.\n- Handshakes for greetings.\n- Lagom (moderation) is valued.",
    'ta': "🇮🇳 Tamil\n- Greet with 'Vanakkam'.\n- Remove footwear before entering.\n- Address elders with respect.",
    'te': "🇮🇳 Telugu\n- Greet with 'Namaskaram'.\n- Use right hand for gifts or eating.\n- Respect elders with formal speech.",
    'th': "🇹🇭 Thai\n- Wai (palms together bow) greeting.\n- Don’t touch anyone’s head.\n- Take off shoes before entering homes/temples.",
    'tr': "🇹🇷 Turkish\n- Greet with a handshake or cheek kiss.\n- Bring small gifts when visiting.\n- Tea is often offered to guests.",
    'uk': "🇺🇦 Ukrainian\n- Greet with firm handshake.\n- Bring flowers (odd number) if visiting.\n- Toasting is common at meals.",
    'ur': "🇵🇰 Urdu\n- Greet with 'As-salamu alaykum'.\n- Remove shoes before entering homes.\n- Show deep respect to elders.",
    'vi': "🇻🇳 Vietnamese\n- Bow slightly for greeting.\n- Don’t touch an adult’s head.\n- Use both hands when giving or receiving items.",
}
