tips.update({
    'ar': "🌐 Arabic\n- Respect local customs and greetings.\n- Learn basic polite phrases in Arabic.\n- Be aware of body language and personal space norms.",
    'bn': "🌐 Bengali\n- Respect local customs and greetings.\n- Learn basic polite phrases in Bengali.\n- Be aware of body language and personal space norms.",
    'bg': "🌐 Bulgarian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Bulgarian.\n- Be aware of body language and personal space norms.",
    'zh-TW': "🌐 Chinese (Traditional)\n- Respect local customs and greetings.\n- Learn basic polite phrases in Chinese (Traditional).\n- Be aware of body language and personal space norms.",
    'hr': "🌐 Croatian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Croatian.\n- Be aware of body language and personal space norms.",
    'cs': "🌐 Czech\n- Respect local customs and greetings.\n- Learn basic polite phrases in Czech.\n- Be aware of body language and personal space norms.",
    'da': "🌐 Danish\n- Respect local customs and greetings.\n- Learn basic polite phrases in Danish.\n- Be aware of body language and personal space norms.",
    'nl': "🌐 Dutch\n- Respect local customs and greetings.\n- Learn basic polite phrases in Dutch.\n- Be aware of body language and personal space norms.",
    'et': "🌐 Estonian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Estonian.\n- Be aware of body language and personal space norms.",
    'tl': "🌐 Filipino (Tagalog)\n- Respect local customs and greetings.\n- Learn basic polite phrases in Filipino (Tagalog).\n- Be aware of body language and personal space norms.",
    'fi': "🌐 Finnish\n- Respect local customs and greetings.\n- Learn basic polite phrases in Finnish.\n- Be aware of body language and personal space norms.",
    'el': "🌐 Greek\n- Respect local customs and greetings.\n- Learn basic polite phrases in Greek.\n- Be aware of body language and personal space norms.",
    'gu': "🌐 Gujarati\n- Respect local customs and greetings.\n- Learn basic polite phrases in Gujarati.\n- Be aware of body language and personal space norms.",
    'he': "🌐 Hebrew\n- Respect local customs and greetings.\n- Learn basic polite phrases in Hebrew.\n- Be aware of body language and personal space norms.",
    'hu': "🌐 Hungarian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Hungarian.\n- Be aware of body language and personal space norms.",
    'id': "🌐 Indonesian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Indonesian.\n- Be aware of body language and personal space norms.",
    'ko': "🌐 Korean\n- Respect local customs and greetings.\n- Learn basic polite phrases in Korean.\n- Be aware of body language and personal space norms.",
    'lv': "🌐 Latvian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Latvian.\n- Be aware of body language and personal space norms.",
    'lt': "🌐 Lithuanian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Lithuanian.\n- Be aware of body language and personal space norms.",
    'ms': "🌐 Malay\n- Respect local customs and greetings.\n- Learn basic polite phrases in Malay.\n- Be aware of body language and personal space norms.",
    'ml': "🌐 Malayalam\n- Respect local customs and greetings.\n- Learn basic polite phrases in Malayalam.\n- Be aware of body language and personal space norms.",
    'mr': "🌐 Marathi\n- Respect local customs and greetings.\n- Learn basic polite phrases in Marathi.\n- Be aware of body language and personal space norms.",
    'mn': "🌐 Mongolian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Mongolian.\n- Be aware of body language and personal space norms.",
    'ne': "🌐 Nepali\n- Respect local customs and greetings.\n- Learn basic polite phrases in Nepali.\n- Be aware of body language and personal space norms.",
    'no': "🌐 Norwegian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Norwegian.\n- Be aware of body language and personal space norms.",
    'fa': "🌐 Persian (Farsi)\n- Respect local customs and greetings.\n- Learn basic polite phrases in Persian (Farsi).\n- Be aware of body language and personal space norms.",
    'pl': "🌐 Polish\n- Respect local customs and greetings.\n- Learn basic polite phrases in Polish.\n- Be aware of body language and personal space norms.",
    'pa': "🌐 Punjabi\n- Respect local customs and greetings.\n- Learn basic polite phrases in Punjabi.\n- Be aware of body language and personal space norms.",
    'ro': "🌐 Romanian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Romanian.\n- Be aware of body language and personal space norms.",
    'sr': "🌐 Serbian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Serbian.\n- Be aware of body language and personal space norms.",
    'si': "🌐 Sinhala\n- Respect local customs and greetings.\n- Learn basic polite phrases in Sinhala.\n- Be aware of body language and personal space norms.",
    'sk': "🌐 Slovak\n- Respect local customs and greetings.\n- Learn basic polite phrases in Slovak.\n- Be aware of body language and personal space norms.",
    'sl': "🌐 Slovenian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Slovenian.\n- Be aware of body language and personal space norms.",
    'sw': "🌐 Swahili\n- Respect local customs and greetings.\n- Learn basic polite phrases in Swahili.\n- Be aware of body language and personal space norms.",
    'sv': "🌐 Swedish\n- Respect local customs and greetings.\n- Learn basic polite phrases in Swedish.\n- Be aware of body language and personal space norms.",
    'ta': "🌐 Tamil\n- Respect local customs and greetings.\n- Learn basic polite phrases in Tamil.\n- Be aware of body language and personal space norms.",
    'te': "🌐 Telugu\n- Respect local customs and greetings.\n- Learn basic polite phrases in Telugu.\n- Be aware of body language and personal space norms.",
    'th': "🌐 Thai\n- Respect local customs and greetings.\n- Learn basic polite phrases in Thai.\n- Be aware of body language and personal space norms.",
    'tr': "🌐 Turkish\n- Respect local customs and greetings.\n- Learn basic polite phrases in Turkish.\n- Be aware of body language and personal space norms.",
    'uk': "🌐 Ukrainian\n- Respect local customs and greetings.\n- Learn basic polite phrases in Ukrainian.\n- Be aware of body language and personal space norms.",
    'ur': "🌐 Urdu\n- Respect local customs and greetings.\n- Learn basic polite phrases in Urdu.\n- Be aware of body language and personal space norms.",
    'vi': "🌐 Vietnamese\n- Respect local customs and greetings.\n- Learn basic polite phrases in Vietnamese.\n- Be aware of body language and personal space norms."
})
